// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Artboard: typeof import('./../components/Artboard/index.vue')['default']
    Laser: typeof import('./../components/Laser/index.vue')['default']
    Nav: typeof import('./../components/Nav/index.vue')['default']
  }
}

export { }
