// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Artboard: typeof import('./../components/Artboard/index.vue')['default']
    Hashboard: typeof import('./../components/Hashboard/index.vue')['default']
    Laser: typeof import('./../components/Laser/index.vue')['default']
    Nav: typeof import('./../components/Nav/index.vue')['default']
    Shot: typeof import('./../components/Shotboard/Shot.vue')['default']
    Shotboard: typeof import('./../components/Shotboard/index.vue')['default']
    WorldBox: typeof import('./../components/WorldBox/index.vue')['default']
  }
}

export { }
